name: Sub Workflow

on:
  workflow_call:
    inputs:
      data:
        required: true
        type : string

jobs:
  sub_job:
    runs-on: ubuntu-latest

    steps:
     - name: ip_addr
       run: |
         echo "Processing data: ${{ inputs.data }}"