name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: true

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/sample2.yml
    with:
      data: ${{ github.event.inputs.user_input }}