name: Trial to create VM and run sanity

on:
  workflow_dispatch:
  

jobs:
  createvm:
    uses: ./.github/workflows/create_vm.yml

  # job2 must run with IP address from inside job1
  sanity:
    needs: createvm
    uses: ./.github/workflows/sanity.yml