name: Trial to create VM and run sanity

on:
  workflow_dispatch:
  

jobs:
  createvm:
    uses: ./.github/workflows/create_vm.yml

  # job2 must run with IP address from inside job1
  sanity:
    needs: createvm
    uses: ./.github/workflows/sanity.yml

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}

  job4:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ needs.job2.outputs.thirdword}} ${{ needs.job2.outputs.forthword }}
