name: sanity 

on:
  workflow_call:
    inputs:
      ip_address:
        type: string
        required: true

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    steps:
      - name: use the ip
        run: echo "${{ inputs.ip_address }}"
