name: sanity 

on:
  workflow_call:

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    steps:
      - id: step3
        run: echo "thirdword=this" >> $GITHUB_OUTPUT
      - id: step4
        run: echo "forthword=is bottle" >> $GITHUB_OUTPUT