name: example_workflow

on:
  workflow_dispatch:
    inputs:
      data:
        description: "Please enter the data"
        type: string

jobs:
  setup-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3