name: Workflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Input for Workflow Call'
        required: true

jobs:
  workflow_dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Workflow Call
        id: workflow_call
        run: |
          echo "::set-output name=my_input::${{ github.event.inputs.my_input }}"
