name: another-workflow

on:
  push:
    branches:
      - main

jobs:
  another-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Input Data
        run: |
          echo "Input data: ${{ inputs.input_data }}"
