name: Workflow Call Example

on:
  workflow_dispatch:

jobs:
  workflow_call_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Input
        run: |
          echo "Input from Workflow Dispatch: ${{ needs.workflow_dispatch.outputs.my_input }}"
