name: example_workflow

on:
  workflow_dispatch:
    inputs:
      data:
        description: "Please enter the data"
        type: string

jobs:
  setup-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Input Data
        id: get-data
        run: |
          echo "::set-output name=data::${{ github.event.inputs.data }}"
          
      - name: Call Another Workflow
        uses: owner/repo/.github/workflows/another-workflow.yml
        with:
          input_data: ${{ steps.get-data.outputs.data }}
