name: Workflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Input for Workflow Call'
        required: true

jobs:
  workflow_dispatch_job:
      uses: ./.github/workflows/workflow_call.yml