name: Workflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Input for Workflow Call'
        required: true

jobs:
  workflow_dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Dispatch Workflow Call
        uses: ./.github/workflows/workflow_call.yml
        with:
          my_input: ${{ github.event.inputs.my_input }}
