name: Workflow Dispatch Example

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Input for Workflow Call'
        required: true

jobs:
  workflow_dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Input as Environment Variable
        run: |
          echo "INPUT_MY_INPUT=${{ github.event.inputs.my_input }}" >> $GITHUB_ENV
      - name: Upload Environment File
        uses: actions/upload-artifact@v2
        with:
          name: environment
          path: $GITHUB_ENV
