name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: true

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/workflow_call.yml
    id: call_workflow # Corrected identifier
    with:
      data: ${{ github.event.inputs.user_input }}

  main_job:
    needs: call-workflow-passing-data
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve sub workflow data
        run: |
          sub_workflow_data="${{ fromJson(needs.call_workflow.outputs.workflow_data) }}" # Corrected identifier
          echo "Sub Workflow Data: $sub_workflow_data"
